### ISSUE TITLE
install-pi.sh stops on non-existent path

### ISSUE THREAD

**Issue by honyczek** [lupyuen/pinetime-rust-mynewt#14] opened 2020-07-17 12:18 UTC
```
----- Installing openocd-spi...
+ '[' '!' -d /home/pi/openocd-spi ']'
+ cp /home/pi/openocd-spi/src/openocd /home/pi/pinetime-rust-mynewt/openocd/bin/openocd
cp: cannot create regular file '/home/pi/pinetime-rust-mynewt/openocd/bin/openocd': No such file or directory
```

At first I had this script in subdirectory /home/pi/PineTime/pinetime-rust-mynewt/scripts/, so I moved the solution to /home/pi/ but the issue was still there. So I created directory openocd/bin by `mkdir -p ../openocd/bin` and run the script install-pi.sh again and it worked.

Expected behavior:
1. script will autodetect path.
2. required directory will be autocreated

**Comment by lupyuen** [comment] 2020-07-18 05:09
Thanks! Lemme find a good way to fix this. We will have to create the directory `/home/pi/pinetime-rust-mynewt/openocd/bin` if it doesn't exist.

I will have to do regression testing, which means installing a fresh Raspberry Pi from scratch with a new SD card. Wonder if there's a simpler way...

**Comment by honyczek** [comment] 2020-07-21 12:19
When I tested it again on the fresh install of Raspberry Pi and Raspbian, this issue is still there.

**Comment by lupyuen** [comment] 2020-07-21 14:34
Yep not fixed yet :-)

**Comment by lupyuen** [comment] 2020-10-19 09:35
Closing this issue because pinetime-rust-mynewt has been revamped for educational use.

**Closed as completed by lupyuen** 2020-10-19 09:35 UTC
